name: qr_scenear
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  share_plus: ^13.3.0
  mobile_scanner: ^7.4.0
  url_launcher: ^6.3.2
  gal: ^2.3.3
  screenshot: ^3.0.0
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/kopsay_logo.png
    - assets/images/kopsay_logo1.png
  uses-material-design: true

flutter_native_splash:
  color: "#F7F9FC"
  image: assets/images/kopsay_logo.png
  android: true
  ios: true
  android_12:
    color: "#F7F9FC"
    image: assets/images/kopsay_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/kopsay_logo1.png"
